
### Getting all the users
GET http://localhost:3001/api/user/all
Content-Type: application/json

### Getting a user by id
GET http://localhost:3001/api/user/3
Content-Type: application/json


### Creating the user

POST http://localhost:3001/api/user/create
Content-Type: application/json

{
    "firstName": "Name3",
    "lastName": "LastName3",
    "email": "name3@gmail.com"
}


### Updating a user

PUT http://localhost:3001/api/user/3/update
Content-Type: application/json

{
  "firstName": "Name0",
  "lastName": "LastName0"
}

### Deleting a user

DELETE http://localhost:3001/api/user/3/delete
Content-Type: application/json
