### all todos
GET http://localhost:3001/todos

### Single todo

GET http://localhost:3001/todo/62dc2c8a1a1a47894e552699



### Creating todo
POST http://localhost:3001/todo/create
Content-Type: application/json

{
    "title":"eating",
    "completed": false
}

