-- CREATING A TABLE OF USERS

CREATE DATABASE auth_user;
DROP TABLE auth_user;
CREATE TABLE auth_user(
    id BIGSERIAL PRIMARY KEY NOT NULL,
    password TEXT NOT NULL,
    createdAt DATE NOT NULL DEFAULT NOW(),
    username TEXT NOT NULL UNIQUE,
    email text NOT NULL
);